# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13b930e761322e7b931f7580783d791e08e1c2848bf9390569f4ff430edcb231641d0600a1c110eb1ce3ad1b7e1159f904605addafbda2cfbc5953fe845f96b9

test:
  secret_key_base: 1d355adac091842bf870e4d2d765d46042b645ea69d5c8d24f6f2012a4117bac3f5fc5f1ca1fd299eab41beb86cec93085d7b96815c2e783c60b3c5afe38098a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
